version: '3.8'

services:
  redis-cluster:
    image: grokzen/redis-cluster:7.0.10
    container_name: redis-cluster
    environment:
      - IP=0.0.0.0
      - CLUSTER_ONLY=true
      - CLUSTER_ANNOUNCE_IP=127.0.0.1
      - CLUSTER_ANNOUNCE_PORT=7000
    network_mode: host
    restart: unless-stopped

  mysql:
    image: mysql:8.4.4
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hr
    network_mode: host
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-server
    depends_on:
      - redis-cluster
      - mysql
    # 在 host 模式下，ports 選項會被忽略，但只要 API Server 綁定在 0.0.0.0:8080，
    # 主機上的 127.0.0.1:8080 就能直接訪問到
    environment:
      - SERVER_NAME=hr-system-local
      - SERVER_PORT=8080
      - SERVER_VERSION=v0.0.0
      - LOG_LEVEL=debug
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=hr
      - MYSQL_MaxIdle=5
      - MYSQL_MaxOpen=10
      - REDIS_CLUSTER_ADDR=127.0.0.1
      - REDIS_CLUSTER_PORT=7000
    command: ["/bin/sh", "-c", "sleep 10 && ./api_server"]
    network_mode: host
    restart: unless-stopped