version: '3.8'

services:
  redis-cluster:
    image: grokzen/redis-cluster:7.0.10
    container_name: redis-cluster
    environment:
      - CLUSTER_ONLY=true
      - CLUSTER_ANNOUNCE_IP=redis-cluster  
      - CLUSTER_ANNOUNCE_PORT=7000
    ports:
      - "7000-7005:7000-7005"
    networks:
      - my_network
    restart: unless-stopped

  mysql:
    image: mysql:8.4.4
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hr
    ports:
      - "3306:3306"
    networks:
      - my_network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-server
    depends_on:
      - redis-cluster
      - mysql
    ports:
      - "8080:8080"
    environment:
      - SERVER_NAME=hr-system-local
      - SERVER_PORT=8080
      - SERVER_VERSION=v0.0.0
      - LOG_LEVEL=debug
      - MYSQL_HOST=mysql-local
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=hr
      - MYSQL_MaxIdle=5
      - MYSQL_MaxOpen=10
      - REDIS_CLUSTER_ADDR=redis-cluster
      - REDIS_CLUSTER_PORT=7000
      - SEED_DATA_ENABLED=true
    command: ["/bin/sh", "-c", "sleep 10 && ./api_server"]
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    driver: bridge
